services:
  postgres:
    image: postgres:16-alpine
    container_name: hc-postgres
    environment:
      POSTGRES_USER: sandbox
      POSTGRES_PASSWORD: sandbox
      POSTGRES_DB: sandbox
    ports:
      - "5499:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./infra/pg/init:/docker-entrypoint-initdb.d
    command: >
      postgres
        -c shared_preload_libraries=pg_stat_statements
        -c pg_stat_statements.track=all
        -c pg_stat_statements.max=10000
        -c track_io_timing=on
        -c log_min_duration_statement=1000
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sandbox -d sandbox"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: hc-redis
    ports:
      - "6399:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pg_data:
  redis_data:
